# url: https://y7kim.github.io
# baseurl: /

# -------------------------------
#  Content
# -------------------------------
# t:
#   pt-br:
    title: Luiza Vieira
    # email: your-email@domain.com
    description: "Swimming coach. Better results for the best sport."
    text: "Swimming coach"
    subtext: "Os melhores resultados para o melhor esporte"
    button: "Saiba mais"

    section-services:
      title: Serviços
      description: "Consultoria Online Personalizada"
      services:
        - title: Treinos de Natação
          description: A consultoria online para treinos de natação é totalmente individualizada e específica de acordo com o objetivo do aluno para as piscinas, seja ele voltado para a prática competitiva, lúdica ou para o bem-estar.
          ico: trophy
        - title: Preparação Física direcionada à Natação
          description: A organização dos treinos físicos é direcionada aos praticantes que já possuem certa experiência com a Natação e almejam aperfeiçoar o desempenho nas piscinas.
          ico: heartbeat


    # Team names, titles and social links
    section-team:
      title: "Contato"
      description: "Para mais informações:"
      end: ""
      people:
      - name: Luiza Vieira
        pic: coach
        position: Swimming coach
        social:
          - title: facebook
            url: https://facebook.com/luiza.ferreiravieira
          - title: twitter
            url: https://twitter.com/luizafvieira
          - title: instagram
            url: https://instagram.com/luizavieira_swimcoach
          - title: whatsapp
            url: https://bit.ly/luizavieira

    section-portifolio:
        title: "O que é"
        description: ""

    section-about:
      title: "Minha história"
      description: ""
      timeline:
        - title: 'Natação da UFMG'
          timewindow: 2014 – 2018
          pic: 1
          description: "Head coach da equipe de natação da UFMG. Equipe tetra campeã do estadual universitário, além de figurar entre as top 5 do Brasil desde 2014, sendo a melhor IES pública federal em todas as participações em campeonatos nacionais."
        - title: 'Team GB'
          timewindow: 2016
          pic: 2
          description: "Auxiliar da seleção britânica de natação que competiu nos Jogos Olímpicos – Rio 2016. O time britânico fez a sua preparação para os Jogos no Centro de Treinamento Esportivo da UFMG nos meses de novembro de 2015, junho e julho de 2016."
        - title: 'Mestrado em Ciências do Esporte'
          timewindow: 2017
          pic: 3
          description: "Ano em que conquistei o título de Mestre em Ciências do Esporte. Caminhada acadêmica que teria um grande progresso nos anos seguintes."
        - title: 'Temporada com Atleta Olímpica'
          timewindow: 2017
          pic: 4
          description: "Auxiliar técnico da nadadora olímpica Joanna Maranhão. Na temporada em que a atleta alcançou seus melhores tempos da vida em suas principais provas, eu pude acompanhá-la de perto e contribuir para que o desempenho fosse otimizado a todo momento."
        - title: ''
          timewindow: 2018 – 2019
          pic: 5
          description: "Início dos estudos para ingressar no Doutorado na Università degli Studi Di Roma Tor Vergata, em Roma – Itália."
# # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# -------------------------------
# Build settings
# -------------------------------
markdown: kramdown
permalink: pretty
